services:
  - type: web
    name: spectabas
    env: elixir
    buildCommand: "mix deps.get && mix assets.build && mix phx.digest"
    startCommand: "mix eval 'Spectabas.Release.migrate()' && mix phx.server"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spectabas-db
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        value: www.spectabas.com
      - key: CLICKHOUSE_URL
        fromService:
          name: spectabas-clickhouse
          type: pserv
          property: hostport
      - key: CLICKHOUSE_DB
        value: spectabas
      - key: CLICKHOUSE_WRITER_USER
        sync: false
      - key: CLICKHOUSE_WRITER_PASSWORD
        sync: false
      - key: CLICKHOUSE_READER_USER
        sync: false
      - key: CLICKHOUSE_READER_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false

  - type: pserv
    name: spectabas-clickhouse
    env: docker
    dockerfilePath: ./clickhouse/Dockerfile
    disk:
      name: clickhouse-data
      mountPath: /var/lib/clickhouse
      sizeGB: 20

databases:
  - name: spectabas-db
    databaseName: spectabas
    user: spectabas
