defmodule Spectabas.Insights do
  @moduledoc """
  Per-site stream of actionable signals — anomalies, goal-pace changes,
  AI weekly summaries, conversion milestones — that the dashboard
  surfaces between the user's weekly insight emails.

  Insights are generated by `Workers.InsightsGenerator` (daily cron) from
  the various detection systems (`AnomalyDetector`, goal stats, AI
  weekly content, etc.) and enriched async by `Workers.InsightExplainer`
  which writes a one-paragraph plain-English `explanation` field via
  Anthropic Haiku.

  Insights are append-only at write time and per-user dismiss at read
  time (see `Spectabas.Insights.Dismissal`).
  """

  import Ecto.Query
  alias Spectabas.{Repo, Insights}
  alias Spectabas.Insights.{Insight, Dismissal}

  @valid_kinds ~w(anomaly_spike anomaly_drop goal_pace ai_weekly_summary conversion_milestone)
  @valid_severities ~w(info notice warning)

  @doc "All valid `kind` values currently emitted by the generator."
  def valid_kinds, do: @valid_kinds

  @doc "All valid `severity` values."
  def valid_severities, do: @valid_severities

  @doc """
  Insert an insight. Idempotent on `(site_id, kind, dedupe_key)` — if the
  generator runs twice in the same day with the same dedupe key, the
  second call silently returns the existing row instead of erroring.

  After insert, callers should enqueue `Workers.InsightExplainer` for
  anomaly kinds to fill in the AI explanation asynchronously.
  """
  def create(attrs) when is_map(attrs) do
    %Insight{}
    |> Insight.changeset(attrs)
    |> Repo.insert(
      on_conflict: {:replace, [:title, :body, :data, :severity, :updated_at]},
      conflict_target: [:site_id, :kind, :dedupe_key],
      returning: true
    )
  end

  @doc """
  List insights for a site that the given user hasn't dismissed.
  Newest first. Optional `:limit` (default 50).
  """
  def list_active_for_user(site_id, user_id, opts \\ []) do
    limit = Keyword.get(opts, :limit, 50)

    from(i in Insight,
      where: i.site_id == ^site_id,
      where:
        i.id not in subquery(
          from(d in Dismissal, where: d.user_id == ^user_id, select: d.insight_id)
        ),
      order_by: [desc: i.inserted_at],
      limit: ^limit
    )
    |> Repo.all()
  end

  @doc "All insights for a site, ignoring dismissals (admin / debugging)."
  def list_all_for_site(site_id, opts \\ []) do
    limit = Keyword.get(opts, :limit, 100)

    from(i in Insight,
      where: i.site_id == ^site_id,
      order_by: [desc: i.inserted_at],
      limit: ^limit
    )
    |> Repo.all()
  end

  @doc "Fetch a single insight by id (with site scope check)."
  def get_for_site(site_id, id) do
    Repo.get_by(Insight, id: id, site_id: site_id)
  end

  @doc """
  Dismiss an insight for a user. Idempotent — clicking dismiss twice is
  a no-op rather than an error.
  """
  def dismiss(insight_id, user_id) do
    %Dismissal{}
    |> Dismissal.changeset(%{insight_id: insight_id, user_id: user_id})
    |> Repo.insert(
      on_conflict: :nothing,
      conflict_target: [:insight_id, :user_id]
    )
  end

  @doc "Undo a dismiss (rarely used; mostly for tests)."
  def undismiss(insight_id, user_id) do
    from(d in Dismissal,
      where: d.insight_id == ^insight_id and d.user_id == ^user_id
    )
    |> Repo.delete_all()

    :ok
  end

  @doc """
  Update the `explanation` field on an insight. Called by
  `Workers.InsightExplainer` after the Anthropic call completes.
  """
  def set_explanation(%Insight{} = insight, explanation) when is_binary(explanation) do
    insight
    |> Insight.changeset(%{explanation: explanation})
    |> Repo.update()
  end

  @doc """
  Compute a stable dedupe key from kind + arbitrary context. Same
  context → same key, so re-running the generator doesn't multiply rows.
  """
  def dedupe_key(kind, context) when is_binary(kind) and is_map(context) do
    payload = kind <> ":" <> canonical_json(context)
    :crypto.hash(:sha256, payload) |> Base.encode16(case: :lower) |> String.slice(0..63)
  end

  defp canonical_json(map) do
    # Sorted keys so {"a" => 1, "b" => 2} and {"b" => 2, "a" => 1} hash
    # to the same dedupe key. JSON-encode the value to stringify lists,
    # numbers, etc. consistently.
    map
    |> Enum.sort_by(fn {k, _v} -> to_string(k) end)
    |> Enum.map(fn {k, v} -> "#{k}=#{Jason.encode!(v)}" end)
    |> Enum.join("|")
  end

  @doc false
  def __valid_kinds__, do: Insights.valid_kinds()
end
