defmodule Spectabas.Repo.Migrations.CreateInsights do
  use Ecto.Migration

  def change do
    create table(:insights) do
      add :site_id, references(:sites, on_delete: :delete_all), null: false

      # Kind is a coarse classifier the UI uses to pick an icon + drill-down:
      # "anomaly_spike", "anomaly_drop", "goal_pace", "ai_weekly_summary",
      # "conversion_milestone", etc. Extensible — new kinds just need an
      # icon mapping and a generator path.
      add :kind, :string, size: 40, null: false

      # Visual severity. Maps to verdict ladder color in the UI.
      # "info" (gray/neutral), "notice" (amber), "warning" (red).
      add :severity, :string, size: 20, null: false, default: "info"

      add :title, :string, size: 255, null: false

      # Optional short body (markdown). Often a one-paragraph summary.
      add :body, :text

      # AI-generated explanation, populated asynchronously by
      # `Workers.InsightExplainer`. Null until that job completes;
      # UI shows "Analyzing..." in the meantime.
      add :explanation, :text

      # Structured metric context + drill-down URL.
      # Example: %{"metric" => "pageviews", "current" => 1234,
      # "previous" => 800, "change_pct" => 54.3, "url" => "/dashboard/..."}.
      add :data, :map, default: %{}

      # Idempotent insert key. Generated by the InsightsGenerator from
      # (kind + canonical identifier within that kind) so the same anomaly
      # detected across multiple worker runs in the same day doesn't
      # create duplicate insights.
      add :dedupe_key, :string, size: 128, null: false

      timestamps()
    end

    create index(:insights, [:site_id, :inserted_at])
    create unique_index(:insights, [:site_id, :kind, :dedupe_key])
  end
end
